// Generates iOS app icons from faviconOficial.svg.
// Run: node scripts/generate-icons.js  (from ios-shell/)
// Requires: npm install  (sharp must be present)
//
// After running, open ios/App/App.xcassets/AppIcon.appiconset/ in Xcode
// and drag the generated PNGs into the matching slot, OR use the iOS 14+
// "Single Size" mode and only drop icon-1024.png into the 1024x1024 slot.
//
// The `ios/` folder is generated by `npx cap add ios` and is gitignored —
// this script writes into that generated tree, so re-run after every
// `cap add ios` / `cap sync ios` if icons disappear.

const sharp = require('sharp')
const fs    = require('fs')
const path  = require('path')

const SVG_SRC = path.resolve(__dirname, '../../app/public/faviconOficial.svg')
const OUT_DIR = path.resolve(__dirname, '../ios/App/App.xcassets/AppIcon.appiconset')

// iOS icon sizes (pt). 1024 = App Store marketing icon, must NOT have alpha.
const SIZES = [20, 29, 40, 58, 60, 76, 80, 87, 120, 152, 167, 180, 1024]

// SVG source uses fill="#000000"; rewrite to white so it shows on dark BG
const rawSvg   = fs.readFileSync(SVG_SRC, 'utf8')
const whiteSvg = rawSvg.replace(/fill="#000000"/g, 'fill="#FFFFFF"')
const svgBuf   = Buffer.from(whiteSvg)

// Background = institutional dark green, same as the Android shell.
const BG = '#0f3d2e'

async function makeIconPng(size) {
  const iconPad   = Math.round(size * 0.12)
  const innerSize = size - iconPad * 2

  const bg = Buffer.from(
    `<svg width="${size}" height="${size}" xmlns="http://www.w3.org/2000/svg">
       <rect width="${size}" height="${size}" fill="${BG}" rx="${Math.round(size * 0.22)}"/>
     </svg>`
  )

  const iconResized = await sharp(svgBuf)
    .resize(innerSize, innerSize, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer()

  return sharp(bg)
    .composite([{ input: iconResized, left: iconPad, top: iconPad }])
    .png()
    .toBuffer()
}

async function main() {
  if (!fs.existsSync(OUT_DIR)) {
    console.error(`Missing ${OUT_DIR}`)
    console.error('Run `npx cap add ios` first to scaffold the Xcode project, then re-run this script.')
    process.exit(1)
  }

  for (const size of SIZES) {
    const buf     = await makeIconPng(size)
    const outName = size === 1024 ? 'icon-1024.png' : `icon-${size}.png`
    fs.writeFileSync(path.join(OUT_DIR, outName), buf)
    console.log(`+ ${outName.padEnd(15)} (${size}x${size})`)
  }

  console.log('\nDone. Open Xcode -> AppIcon to assign sizes, or use 1024x1024 single-size mode (iOS 14+).')
}

main().catch(err => { console.error(err); process.exit(1) })
